name: 'Terraform Transactions Deployment'
on: 
    push:
        branches:
            - main
        paths:
            - 'terraform/main.tf'
            - 'transactions/*'
            - 'transactions/backend.tf'
            - 'transactions/terraform.tfvars'

env:
    PROJECT_ID: dulcet-abacus-397714

jobs:
    setup:
        name: 'Setup terraform on GCP'
        permissions:
            contents: 'read'
            id-token: 'write'
        runs-on: ubuntu-latest
        steps:
            - name: Create Terraform
              run: cd ${{runner.temp}}; mkdir terraform
              
            - name: Checkout
              uses: actions/checkout@v3
            
            - name: Copy Terraform files
              run: |
                cp terraform/main.tf ${{runner.temp}}/terraform/main.tf
                cp -R transactions/bigquery ${{runner.temp}}/terraform/
                cp transactions/backend.tf ${{runner.temp}}/terraform/backend.tf
                cp transactions/terraform.tfvars ${{runner.temp}}/terraform/terraform.tfvars

            - name: Check Contents
              run: cd ${{runner.temp}}/terraform ; ls
            
            
            - name: Auth 
              uses:  google-github-actions/auth@v1
              with:
                token_format: 'access_token'
                workload_identity_provider: 'projects/389671115938/locations/global/workloadIdentityPools/my-pool/providers/my-provider'
                service_account: 'gitactions-service@dulcet-abacus-397714.iam.gserviceaccount.com' 
                access_token_lifetime: '30s'
            
            - name: Setup Account
              uses: hashicorp/setup-terraform@v1
              
            - name: Terraform Init
              working-directory: ${{runner.temp}}/terraform
              run: terraform init
            
            - name: Terraform Plan
              working-directory: ${{runner.temp}}/terraform
              run: terraform plan

            - name: Terraform Apply
              working-directory:  ${{runner.temp}}/terraform
              run: terraform apply -auto-approve
