name: 'Terraform Transactions Deployment'
on: 
    push:
        branches:
            - main
        paths:
            - 'terraform/main.tf'
            - 'transactions/*'
            - 'transactions/backend.tf'
            - 'transactions/terraform.tfvars'
            - 'transactions/variables.tf'
            - '.github/workflows/terraform_transactions.yml'


env:
    PROJECT_ID: dulcet-abacus-397714


jobs:
    setup:
        name: 'Setup Bigquery/Cloud-Function on GCP'
        permissions:
            contents: 'read'
            id-token: 'write'
        runs-on: ubuntu-latest
        steps:
            - name: Create Terraform
              run: cd ${{runner.temp}}; mkdir terraform
              
            - name: Checkout
              uses: actions/checkout@v3
            
            - name: Copy Terraform files
              run: |
                cp terraform/main.tf ${{runner.temp}}/terraform/main.tf
                cp -R transactions/bigquery ${{runner.temp}}/terraform/
                cp transactions/backend.tf ${{runner.temp}}/terraform/backend.tf
                cp transactions/terraform.tfvars ${{runner.temp}}/terraform/terraform.tfvars
                cp transactions/variables.tf ${{runner.temp}}/terraform/variables.tf
                cp -R transactions/cloud_function ${{runner.temp}}/terraform/

            - name: Check Contents for BQ
              run: cd ${{runner.temp}}/terraform/bigquery ; ls

            - name: Check Contents for CF1
              run: cd ${{runner.temp}}/terraform/cloud_function/hello1 ; ls 
             
            - name: Check Contents for CF2
              run: cd ${{runner.temp}}/terraform/cloud_function/hello2 ; ls   
            
            - name: Auth 
              uses:  google-github-actions/auth@v1
              with:
                token_format: 'access_token'
                workload_identity_provider: 'projects/389671115938/locations/global/workloadIdentityPools/my-pool/providers/my-provider'
                service_account: 'gitactions-service@dulcet-abacus-397714.iam.gserviceaccount.com' 
                access_token_lifetime: '30s'
            
            - name: Setup Account
              uses: hashicorp/setup-terraform@v1
              
            - name: Terraform Init
              working-directory: ${{runner.temp}}/terraform
              run: terraform init
            
            - name: Terraform Plan
              working-directory: ${{runner.temp}}/terraform
              run: terraform plan

            - name: Terraform Apply
              working-directory:  ${{runner.temp}}/terraform
              run: terraform apply -auto-approve

            - name: Deploy Functions
              run: |
                gcloud functions deploy hello1 \
                  --runtime python311 \
                  --trigger-http \
                  --entry-point hello1 \
                  --allow-unauthenticated \
                  --source ./transactions/cloud_function/hello1/hello1.py
        
                gcloud functions deploy hello2 \
                  --runtime python311 \
                  --trigger-http \
                  --entry-point hello2 \
                  --allow-unauthenticated \
                  --source ./transactions/cloud_function/hello2/hello2.py
